### PR TITLE
$ vs jQuery errors

### PR DESCRIPTION
**Pull request by nathanielks**
fixed errors where $ alias was used instead of jQuery. Useful for WordPress sites that use jQuery in no conflict mode

### CODE REVIEW

**Comment by jpillora** [comment]
Hi Nathaniel, thanks for the PR, I'm doing a big refactor right now and I've added this in on my branch, so I'll merge it in with all of my changes. So it didn't work just changing the `Gruntfile.coffee` ?

**Comment by nathanielks** [comment]
Hah, absolutely! Changing gruntfile did as a matter of fact! Did I leave some things behind? I thought I cleaned up but I mightn't have caught everything.

**Comment by jpillora** [comment]
The 'Files Changed' tab at the top of your PR is your friend ;)

**Comment by nathanielks** [comment]
Ah… very good point… I'd be happy to clean that up fully if you like.  

## 

All the Best,
Nathaniel Schweinberg
http://fightthecurrent.org

**Comment by jpillora** [comment]
Sure, if you like - then I could auto-merge, otherwise I'll just add in that line into my branch - same effect in the end :)

**Comment by nathanielks** [comment]
You know, if you just want to add that line, that'll be simpler =p  

## 

All the Best,
Nathaniel Schweinberg
http://fightthecurrent.org

**Comment by jpillora** [comment]
Done and closed :+1:

**Comment by nathanielks** [comment]
Brilliant :)

**Pull request closed without merging**
